In [4]:
import h5py
import numpy as np
from pathlib import Path
from drqbc.drqv2 import DrQV2Agent
import torch

In [2]:
episodes = h5py.File('/home/jaewoo/research/v-d4rl/vd4rl_data/main/walker_walk/medium/0_walker_walk_medium.hdf5', 'r')
episodes = {k: episodes[k][:] for k in episodes.keys()}

In [3]:
def load_snapshot(snapshot):
    snapshot = Path(snapshot)
    with snapshot.open('rb') as f:
        payload = torch.load(f)
    for k, v in payload.items():
        self.__dict__[k] = v

In [9]:
agent= DrQV2Agent(obs_shape=(3,84,84), action_shape=(6,), device='cuda', lr=0.001, feature_dim=50,
                 hidden_dim=1024, critic_target_tau=0.05, num_expl_steps=2000,
                 update_every_steps=2, stddev_schedule=np.linspace(1.0,0.1,250000), stddev_clip=0.3, use_tb=True)

In [30]:
episodes['observation'].shape
observations = episodes['observation']

In [43]:
start_idx = 0
img = torch.tensor(np.concatenate([observations[0], observations[1], observations[2]])).reshape(1, 9, 84, 84).to('cuda')

In [53]:
payload = torch.load("/home/jaewoo/research/v-d4rl/trained_policy.pt")
encode = payload['agent'].encoder(img)
actor_trunk = payload['agent'].actor.trunk(encode)
critic_trunk = payload['agent'].critic.trunk(encode)
latent = torch.cat([critic_trunk, actor_trunk], axis=-1)

In [104]:
episodes['reward'][:1]

array([0.])

In [92]:
dd[0]['actions'][:10]

array([[ 0.982366  , -0.18254389,  0.8274114 , -0.9747983 ,  0.99314946,
        -0.96083313],
       [ 0.61038136, -0.98506474,  0.4648151 , -0.9690731 ,  0.99509406,
        -0.9969489 ],
       [ 0.00194764, -0.8230907 ,  0.90637624, -0.88778234,  0.98608327,
        -0.9949771 ],
       [-0.14530475,  0.6513372 ,  0.53371745, -0.87331164,  0.6030798 ,
        -0.92264336],
       [ 0.7907376 , -0.6071894 ,  0.89785945, -0.9927168 ,  0.8264251 ,
        -0.98996925],
       [ 0.85198677, -0.29958564,  0.96054316, -0.36060038,  0.98329365,
        -0.09885143],
       [ 0.6752343 ,  0.6231856 ,  0.51286036,  0.00260472,  0.98355436,
        -0.06281596],
       [-0.3526068 , -0.8136092 ,  0.91652507, -0.9388459 ,  0.8199896 ,
        -0.9142404 ],
       [-0.97293216, -0.81375724,  0.74830604, -0.98375255,  0.8418938 ,
        -0.8570895 ],
       [-0.98936206,  0.8724581 ,  0.04215682, -0.91962266, -0.740253  ,
        -0.9828543 ]], dtype=float32)

In [76]:
episodes['observation'][:]

array([[[[ 45,  45,  46, ...,  45,  45,  45],
         [ 44,  44,  44, ...,  44,  44,  44],
         [ 44,  44,  44, ...,  44,  44,  45],
         ...,
         [ 39,  54,  57, ...,  32,  38,  55],
         [ 46,  57,  57, ...,  32,  35,  47],
         [ 52,  57,  57, ...,  32,  32,  40]],

        [[ 67,  67,  68, ...,  67,  67,  67],
         [ 67,  67,  66, ...,  66,  67,  67],
         [ 66,  66,  66, ...,  66,  66,  67],
         ...,
         [ 66,  83,  85, ...,  66,  71,  87],
         [ 73,  84,  85, ...,  66,  68,  79],
         [ 80,  84,  85, ...,  66,  65,  72]],

        [[ 90,  90,  91, ...,  90,  90,  90],
         [ 89,  89,  89, ...,  89,  89,  89],
         [ 88,  88,  88, ...,  88,  88,  89],
         ...,
         [ 94, 111, 114, ...,  98, 103, 119],
         [101, 112, 114, ...,  98, 100, 111],
         [109, 113, 114, ...,  98,  97, 103]]],


       [[[ 45,  45,  46, ...,  45,  45,  45],
         [ 44,  44,  44, ...,  44,  44,  44],
         [ 44,  44,  44, ..., 

In [84]:
dd[3]['observations'].shape

(501, 100)

In [34]:
episodes.keys()

dict_keys(['action', 'discount', 'observation', 'reward', 'step_type'])

In [47]:
episodes['reward'].mean()

0.8411922733194701

In [36]:
np.where(episodes['step_type']==0)

(array([    0,   501,  1002,  1503,  2004,  2505,  3006,  3507,  4008,
         4509,  5010,  5511,  6012,  6513,  7014,  7515,  8016,  8517,
         9018,  9519, 10020, 10521, 11022, 11523, 12024, 12525, 13026,
        13527, 14028, 14529, 15030, 15531, 16032, 16533, 17034, 17535,
        18036, 18537, 19038, 19539, 20040, 20541, 21042, 21543, 22044,
        22545, 23046, 23547, 24048, 24549]),)

In [17]:
np.where(episodes['step_type']==2)[0].shape

(50,)

In [23]:
episodes['observation'].shape

(25050, 3, 84, 84)

In [25]:
episodes['discount']

array([1., 1., 1., ..., 1., 1., 1.])

In [27]:
for i in episodes:
    print(i)

action
discount
observation
reward
step_type


In [1]:
import numpy as np
import torch

/home/jaewoo/anaconda3/envs/augmentation/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [89]:
dd = np.load("/home/jaewoo/research/v-d4rl/encoded_trajectory/offline_walker_walk_medium_ver3.npy", allow_pickle=True)

In [90]:
dd[0]['rewards']

array([[0.33180651],
       [0.33285818],
       [0.35439989],
       [0.37610087],
       [0.36633694],
       [0.38120303],
       [0.3226392 ],
       [0.33913589],
       [0.70062178],
       [0.55574036],
       [0.52131683],
       [0.62041306],
       [0.79693294],
       [0.87032342],
       [0.78682482],
       [0.73677289],
       [0.69649076],
       [0.69979447],
       [0.59495372],
       [0.42210019],
       [0.34083629],
       [0.28312382],
       [0.0916239 ],
       [0.03400521],
       [0.01926884],
       [0.02472807],
       [0.11796129],
       [0.65953612],
       [0.8849932 ],
       [1.15665817],
       [1.09797311],
       [1.04812789],
       [1.31456292],
       [1.73634231],
       [1.79976749],
       [1.67086768],
       [1.57825291],
       [1.42104352],
       [1.2617799 ],
       [1.04070818],
       [0.8131485 ],
       [0.705621  ],
       [0.7127521 ],
       [0.79821527],
       [1.0369668 ],
       [1.24748838],
       [1.37978017],
       [1.438

In [30]:
dd[1]['rewards']

array([[0.69665569],
       [0.59914577],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.45824727],
       [0.36610878],
       [0.40592989],
       [0.42177904],
       [0.27351129],
       [0.184046  ],
       [0.11972306],
       [0.06742811],
       [0.04968196],
       [0.04207779],
       [0.04118055],
       [0.03428853],
       [0.01828579],
       [0.02557516],
       [0.05989226],
       [0.48799047],
       [0.70332897],
       [0.6476171 ],
       [0.71057653],
       [0.72890937],
       [0.76231903],
       [0.91451502],
       [0.98554409],
       [0.98643172],
       [0.98804384],
       [0.99474114],
       [1.12268364],
       [1.25879061],
       [1.36126101],
       [1.32583511],
       [1.17360759],
       [0.99984312],
       [0.91624755],
       [0.98430192],
       [1.02026594],
       [1.04797935],
       [1.00211418],
       [0.9778465 ],
       [0.94994694],
       [0.85681748],
       [0.66985393],
       [0.58615637],
       [0.504